/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapp;

import java.net.ServerSocket;
import java.net.Socket;
import java.io.DataInputStream;
import java.io.DataOutputStream;

/**
 *
 * @author Husnain Raza
 */
public class server_side extends javax.swing.JFrame {

    /**
     * Creates new form server_side
     */
    
    
    static ServerSocket ss;
    static Socket s;
    static DataInputStream data_in;
    static DataOutputStream data_out;
    static String str;
   private static String pc_name="";
    private static int key=0;
   private static String cryptic_msg="";
   private static String decoded_msg="";
   private static String addr_mac="";
   private static int count=0;
    public server_side() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        disp_msg = new javax.swing.JTextArea();
        typed_msg = new javax.swing.JTextField();
        send_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        disp_msg.setEditable(false);
        disp_msg.setColumns(20);
        disp_msg.setRows(5);
        jScrollPane1.setViewportView(disp_msg);

        typed_msg.setText("Type your msg here.....");
        typed_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typed_msgActionPerformed(evt);
            }
        });

        send_btn1.setText("Send");
        send_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btn1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel1.setText("                    SERVER WINDOW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typed_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(send_btn1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typed_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(send_btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typed_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typed_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typed_msgActionPerformed

    private void send_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btn1ActionPerformed
        
        try{
           String send_txt="";
        
        send_txt=typed_msg.getText().trim();
        if(send_txt.equalsIgnoreCase("what is your computer name?") || send_txt.equalsIgnoreCase("what is your mac address?")){
            
            pc_name=send_txt;
        }
                            
        

        
        encryption(send_txt);
        
        data_out.writeUTF(cryptic_msg); // server sending msg to the client..
        
   
    }
    catch(Exception e){}
        
    }//GEN-LAST:event_send_btn1ActionPerformed

    
    
//***************ENCRYPTION*********************
    
    public void encryption(String S){
                cryptic_msg="";
        if(S.equals("what is your computer name?") || S.equals("what is your mac address?")){
        cryptic_msg= S;
        }
        else{
            count++;
            System.out.println("Count is "+count);
            if(count>=6){
            key_change();
            }
    for(int i=0; i<S.length(); i++)
                    {
                                             int asciiValue = S.charAt(i);
                                            asciiValue = key+ asciiValue;
                                            if(asciiValue>126){
                                            asciiValue=(asciiValue%127)+33;   // when ascii exceeds 126 it shows no presentable symbols and addition of 33 is done to bring it under the range of presentable symbols
                                                    }
                                            System.out.println(asciiValue);
                                            cryptic_msg=cryptic_msg+""+(char)asciiValue;
                                            asciiValue=0;
                                            //System.out.println(str.charAt(i) + "=" + asciiValue);
                        }
    System.out.println(cryptic_msg);
        }   
    
        
}
    
    //***************DECRYPTION*********************
 
    
    public static void decryption(String S){
                decoded_msg="";
        if(pc_name.equals("what is your computer name?")){
        decoded_msg= S;
        }
        else if (pc_name.equals("what is your mac address?")){
            addr_mac=S;
        decoded_msg=S;
        pc_name="";
        }
        else{
            count++;
            System.out.println("Count is "+count);
            if(count>=6){
            key_change();
            }
    for(int i=0; i<S.length(); i++)
                    {
                                             int asciiValue = S.charAt(i);
                                             if(asciiValue<key)
                                            asciiValue = key- asciiValue;
                                             
                                             else{
                                                 asciiValue=asciiValue-key;
                                                 if(asciiValue<32)
                                                 asciiValue=(asciiValue%127)+94;   
                                                                                    /* when ascii gets less than 32 it shows no presentable symbols therefore,
                                                                                    addition of 94 is done to bring it under the range of representable symbols
                                                                                                        */
                                             }
                                           
                                            System.out.println("When Key="+key+" is added, Ascii Values will become "+asciiValue);
                                            decoded_msg=decoded_msg+""+(char)asciiValue; //decrypted form of received msg
                                            asciiValue=0;
                                            //System.out.println(str.charAt(i) + "=" + asciiValue);
                        }
    System.out.println("Encrypted form is : "+S);
        }   
    
        
}
 
        
        //***********************************************************************
        
    
    //**************************UPDATING KEY**************************************8
        
    private static void key_change(){
    
                //when count becomes equal to 6
            int sum=0;
            count=0;
            int ctr=0;
            String mac_bit ="";
            addr_mac=addr_mac+"-"; 
            for(int i=0;i<3;i++){
                    
                mac_bit="";
            
                
                StringBuffer sb = new StringBuffer(addr_mac);   //it is used to delete characters from the mac address
                
                if(ctr!=2)        // to ignore the - in mac address
                { mac_bit =""+ addr_mac.charAt(0);}
                sb=sb.deleteCharAt(0);   //deletion takes place
                addr_mac=sb.toString();
                
                System.out.println(addr_mac);
                if(ctr!=2)
                {sum=sum+Integer.parseInt(mac_bit,16);
                addr_mac=addr_mac+mac_bit;}
                
                ctr++;
            }
                if(sum>25){     sum=sum%26;}
                
                key=key+sum;
                sum=0;
                if(key>25){
                key=key%26;
                }
                 System.out.println("NEW KEY IS "+key);
                 System.out.println("NEW MAC ADDRESS "+addr_mac);
        
    }
    
    
    //******************MAIN METHOD
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server_side.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server_side.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server_side.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server_side.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new server_side().setVisible(true);
            }
        });
        String rec_msg="";
        try{
        
            ss=new ServerSocket(1240); // listens at port 1240
            s=ss.accept();      // here connection will be established
            
            data_in=new DataInputStream(s.getInputStream());
            data_out=new DataOutputStream(s.getOutputStream());
            
            while(!rec_msg.equals("exit")){
            
                    rec_msg=data_in.readUTF();
                    
                    
                   decryption(rec_msg);
                    disp_msg.setText(disp_msg.getText().trim()+"\nClient :\t"+decoded_msg);   // displaying the msg
                    
                    
                    //KEY GENERATION
                    
                    if(pc_name.equals("what is your computer name?")){
                        
                       System.out.println("Server Side Backend processes: "); 
                        str=rec_msg;   //storing response from client
                        
                        //adding ASCII VALUES OF THE STRING
                        
  
                          int sum=0;
                          for(int i=0; i<str.length(); i++)
                    {
                                             int asciiValue = str.charAt(i);
                                            sum = sum+ asciiValue;
                                            //System.out.println(str.charAt(i) + "=" + asciiValue);
                        }
                          double avg=sum/str.length();
                          int roundoff=(int) avg;
                          key=roundoff%26;
                          
                         //prints ASCII and KEY , generated by using a certain formula
                                        System.out.println("ASCII of " + str + "=" + sum); 
                                        System.out.println("Key is :"+key);
                        
                    }
            }
        }
        catch(Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea disp_msg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send_btn1;
    private javax.swing.JTextField typed_msg;
    // End of variables declaration//GEN-END:variables
}
